### ISSUE TITLE
React 15.x support release on npm

### ISSUE THREAD

**Issue by doylem** [reactjs/react-tabs#102]
We're having some difficulty upgrading React in our application because the latest version of react-tabs limits us to `0.14.x` 

I can see a commit in master on package.json which bumps support - time for a new tagged release?

Cheers 😄

**Comment by danez** [comment]
We will release as soon as possible.

**Comment by doylem** [comment]
Thanks @danez much appreciated.

**Comment by danez** [comment]
Finally done. 🎉

**Comment by joepvl** [comment]
Awesome! @danez I really appreciate the effort you put in to get this package back into shape. 👍

**Comment by doylem** [comment]
Thanks @danez
