### ISSUE TITLE
Cannot read property 'Tabs' of undefined

### ISSUE THREAD

**Issue by michaelnlindsay** [reactjs/react-tabs#105]
Looks like this issue popped up with version 0.5.4.  The following still works in 0.5.3:

```
import ReactTabs from 'react-tabs';

var Tabs = ReactTabs.Tabs;
var TabList = ReactTabs.TabList;
var TabPanel = ReactTabs.TabPanel;
var Tab = ReactTabs.Tab;
```

But fails with this error on 0.5.4: Uncaught TypeError: Cannot read property 'Tabs' of undefined

**Comment by danez** [comment]
Upds yes it seems that slipped in. I'm going to fix that later. Mean while use
```
import { Tabs, Tab, TabPanel, TabList } from 'react-tabs';
```

**Comment by rahulthampi** [comment]
This issue still persits in npm v1.0.0 of react-tabs. When I checked into the downloaded package in node_modules, I found that TabPanel has been exported twice, each for Tabs & Tabpanel. I apologize for any beginners mistake, cause am a newbie to all of these.. :grimacing:
