### ISSUE TITLE
Customize the styling, see API?

### ISSUE THREAD

**Issue by giladbr** [reactjs/react-tabs#107]
Hey, how can I customize the styling of the tabs?
Also, where can I see an API? Only Inside the "node_modules" files?

**Comment by danez** [comment]
The default style can be easily changed with CSS.
You can also turn of the default style by calling `Tabs. setUseDefaultStyles(false)` once globally.

If you want to use inline styles by suppling the styles prop to the components, wait for the next release which will include this new feature.

**Comment by mustafawm** [comment]
Is there a way to _modify_ `styles.js`? I mean can I make a customized `myStyles.js` (make few small changes) and use that instead?
