### ISSUE TITLE
suggestion about optimization

### ISSUE THREAD

**Issue by LukeLin** [reactjs/react-tabs#113]
using selectedTab in react context so that we don't have to cloneElement, which will lead to re-rendering.And it's easy to support composite component and nested tabs
see: https://github.com/LukeLin/react-tab/blob/master/index.js

**Comment by danez** [comment]
I don't understand what you try to tell us. The cloning os there for good reasons right now, and I can't think of a better solution to change props on children.
How can we avoid calling cloneElement?
