### ISSUE TITLE
React.createElement: type should not be null,

### ISSUE THREAD

**Issue by SylarRuby** [reactjs/react-tabs#116]
I see your examples are using es6, I'm not using es6. Works ok in an es6 project but this project I wont use es6:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Foo`.

```
Tabs = require('react-tabs');
Tab = require('react-tabs');
TabList = require('react-tabs');
TabPanel = require('react-tabs');
...

render: function(){
  return(
   <div>
     <Tabs>
         <TabList>
           <Tab>React</Tab>
         </TabList>

         <TabPanel>
           <h2>react</h2>
         </TabPanel>

       </Tabs>
   </div>
  )
}

...

**Comment by danez** [comment]
Oh sorry for the late reply.

You need to do:

```js
Tabs = require('react-tabs').Tabs;
Tab = require('react-tabs').Tab;
TabList = require('react-tabs').TabList;
TabPanel = require('react-tabs').TabPanel;
...
```

**Comment by SylarRuby** [comment]
Yes, I had to revisit an old project and saw that. But thanks.
