### ISSUE TITLE
Support bootstrap tabs

### ISSUE THREAD

**Issue by shicky** [reactjs/react-tabs#119]
It would be nice to support bootstrap tabs

**Comment by danez** [comment]
Can you explain more? If you want to use bootstrap-tabs, you are free to use them. https://react-bootstrap.github.io/components.html#tabs

**Comment by shicky** [comment]
Yes but react-bootstrap tabs render all tab contents instead of rendering individual tabs.

**Comment by danez** [comment]
Then you should raise this question there and not here. This is a different component.
