### ISSUE TITLE
Tabs content height remains fixed

### ISSUE THREAD

**Issue by vugman** [reactjs/react-tabs#120]
Hi,

The height of the content container is set by the height of the first TabPanel that is shown. 

I have 3 tabs, one of them with very long content.
If I set the initial index to be of the tab with the shorter content, when passing to the tab with the long content, the container's height remains as it was for the first tab and I see only part of the content.

Any ideas?
Thanks!

**Comment by danez** [comment]
Im not sure if it is related to this component. This component doesn't set any height, and my company definitely has this usecase working. Maybe it is some css or javascript outside of react tabs that is having this behavior?
