### ISSUE TITLE
Warnings react 15.2.1

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [reactjs/react-tabs#124]
![3636e3e199474f5a85bec77eebfab4c7](https://cloud.githubusercontent.com/assets/3968373/17254195/6780ab86-55bc-11e6-9f02-746061617361.png)

**Comment by danez** [comment]
The first one was fixed in 0.7, the other one seems to come from other components.

**Comment by Iuriy-Budnikov** [comment]
yes, correct. forgot to slice li.
