### ISSUE TITLE
How to define custom selected tab styles?

### ISSUE THREAD

**Issue by xiebaochun** [reactjs/react-tabs#127]
As the title, thanks advance!

**Comment by joepvl** [comment]
You can do this with a stylesheet. By default, the class `ReactTabs__Tab--selected` is added to the selected tab, but you can change this to a custom class by passing `activeTabClassName` to `<TabList>`, for example like so:

```jsx
<Tabs>
  <TabList activeTabClassName='is-selected'>
    <Tab>Tab 1</Tab>
    <Tab>Tab 2</Tab>
  </TabList>
  <TabPanel>Panel 1</TabPanel>
  <TabPanel>Panel 2</TabPanel>
</Tabs>
```

In this example, the selected tab will have the class `is-selected` added to it, _instead of_ the default.

See https://github.com/reactjs/react-tabs/blob/2963a8c527c5e0c70e159c908b9b3a7ed39f5d0a/src/components/Tab.js#L30 for a bit of context.

PS I don't think there's a(n easy) way to do this through inline styles.

**Comment by xiebaochun** [comment]
@joepvl  It's useful to me, thanks a lot!

**Comment by ekohl** [comment]
It looks like it's not possible to change the TabPanel classes in a similar way. Am I hijacking this issue if I ask for that to be implemented here?

**Comment by joepvl** [comment]
@ekohl kind of! 😄  The feature totally makes sense to me though, would you be willing to create a new issue for it?

**Comment by danez** [comment]
I think the initial issue is reoslved. So I close this.

**Comment by Frikster** [comment]
For anyone else landing here from the internet where the above did not work, in my case I had to do:

```
// JS
import styles from '../location/of/your/less/file.less';

<div className={styles.tabContainer}>
  <Tabs>
    <TabList activeTabClassName='is-selected'>
      <Tab>Tab 1</Tab>
      <Tab>Tab 2</Tab>
    </TabList>
    <TabPanel>Panel 1</TabPanel>
    <TabPanel>Panel 2</TabPanel>
  </Tabs>
</div>

// css
.tabContainer :global .ReactTabs__TabList {
 // your custom style goes here
}

.tabContainer :global .ReactTabs__Tab {
 // your custom style goes here
}

.tabContainer :global .ReactTabs__Tab.ReactTabs__Tab--selected {
  // your custom style goes here
}

.tabContainer :global .ReactTabs__Tab:focus {
  // your custom style goes here
}

.tabContainer :global .ReactTabs__Tab:focus:after {
  // your custom style goes here
}

```
