### ISSUE TITLE
Cleanup examples and use them for website

### ISSUE THREAD

**Issue by danez** [reactjs/react-tabs#133]
Currently the website uses react 0.11 and an old version of react-tabs (see gh-pages branch)

Would be nice to get the current examples up and running in a single page with descriptions what every example is doing and style adjustments.

**Comment by newyork-anthonyng** [comment]
Hi @danez 
I'd like to work on this sometime this week if nobody else has started on it.

**Comment by danez** [comment]
Yeah awesome, if you need any input you can always ask, or create an incomplete PR and ask in there. 👍

**Comment by newyork-anthonyng** [comment]
@danez I was looking into using gitbooks to create the API documentation for react-tabs. See [here](https://newyork-anthonyng.github.io/gitbooks_test/index.html) for what I've worked on so far.

I was planning on using create-react-app to recreate the examples that we have and link to them inside our docs (similar to how the Redux API documentation presents it example code). 

Let me know if this is headed in the right direction.

**Comment by danez** [comment]
Wow this is truly amazing... I did not expect that :)

Can this be hosted also on github pages?

**Comment by newyork-anthonyng** [comment]
@danez I looked into it and I don't think the examples itself could be hosted onto GitHub pages. 

An alternative is to have an `examples` section that describes example use cases of react-tabs, and links them to correct directory in the GitHub repo. This way, the user could just clone the repo and play with the example on their local machine. What are your thoughts on doing this?

**Comment by duranhumes** [comment]
Is this issue still alive?
