### ISSUE TITLE
Window Scroll Top To The Highest Tab Panel

### ISSUE THREAD

**Issue by rizkiandrianto** [reactjs/react-tabs#138]
When I had content with React Highcharts, it always scroll to the highest tab panel. Anyone?

**Comment by danez** [comment]
react-tabs is not doing anything with scrolling, so the problem you have might come from somewhere else.

**Comment by rizkiandrianto** [comment]
Ah I See, Thanks @danez

**Comment by Piero87** [comment]
@rizkiandrianto have you solve the problem? I have the same problem too

**Comment by ilyjs** [comment]
@Piero87 
I answered here https://github.com/kirjs/react-highcharts/issues/358
