### ISSUE TITLE
Maintaining state within tabs

### ISSUE THREAD

**Issue by Method-X** [reactjs/react-tabs#144]
For example, I have forms within my tabs and the user switches between tabs frequently. Sending state back to my parent component can get extremely verbose and complicated. Is there an easy way to maintain state within each tab?

**Comment by themre** [comment]
I solved this by using prop `forceRenderTabPanel={true}` which doesn't force rerender of tabs, but only hides content. hope it helps. otherwise I would advise you to use some redux-forms.

**Comment by Method-X** [comment]
Ah, too bad there wasn't a way to render the Tab Panel once and then it's state is automatically maintained in the parent Tabs component.

**Comment by themre** [comment]
how would parent tab know about the state of each children in tabpanel? each tab is served only as a holder for children, you can't have them linked to a parent. you can always use `onSelect(index, last)` method to handle state of each TabPanel children.
if there isn't any more problems, I suggest we close the issue.

**Comment by euandrei** [comment]
It might sound foolish, but I same question I had many times over forms, or selections in tabs. I solved it by using css tabs.
