### ISSUE TITLE
Tabs.handleClick changes selected tab on ctrl+click or middle click

### ISSUE THREAD

**Issue by briansteffens** [reactjs/react-tabs#145]
Usually when you ctrl+click or middle click a link in a browser, it opens the link in another tab. Clicking a react-tabs tab in this way does this but also changes the selected tab in the original page.

What I expected to happen on ctrl+click/middle click:
- No change to current page.
- New browser-level tab should open with the clicked-on tab selected.

What actually happens:
- The tab I clicked on looks like it's selected, even though the tab content doesn't update.
- New browser-level tab opens with the clicked-on tab selected.

Removing the following handler changes the behavior to what I expected:

https://github.com/reactjs/react-tabs/blob/master/src/components/Tabs.js#L277-L290

It seems that the Tabs.handleClick function is updating the selected tab in response to a click. Why is that being done in response to a click event rather than at render time?

**Comment by newyork-anthonyng** [comment]
@briansteffens 
I'm trying to do ctrl+click (cmd+click on my Mac) on the react tabs, but it's not opening up in a new Browser tab for me. It's acting as if a regular click happened.

Does this ctrl+click functionality still work for you? On the example page (https://reactcommunity.org/react-tabs/example/) for instance?

**Comment by briansteffens** [comment]
I should have tried that example page before opening the issue, looks like the ctrl+click behavior I noticed was due to something else unrelated to react-tabs. I'm going to close the issue. Thanks for looking into this!
