### ISSUE TITLE
Replace className?

### ISSUE THREAD

**Issue by schoenwaldnils** [reactjs/react-tabs#155]
Hi,
what speaks against replacing the className in Tabs, TabList, Tab, TabPanel rather than extending them?
I changed the classes [the way I like them](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md) 
.. but still have the BEM-styled classes in the DOM.
For the sake of beauty of the code, is there a need for the BEM-Classes?

**Comment by lautarodragan** [comment]
Have you tried `Tabs.setUseDefaultStyles(false);`? Notice that it's a call on the class, not an instance.

**Comment by schoenwaldnils** [comment]
@lautarodragan Yes, I already did that. I use my own styles. 
It may seem a bit picky, but I wish to remove the default classes.

Currently I've got this:
```
<Tabs className="ReactTabs">
  <TabList
    className="ReactTabs-list"
    activeTabClassName="is-active"
    disabledTabClassName="is-disabled"
  >
...
```
and get (simplified): 
```
<div class="ReactTabs react-tabs ReactTabs">
  <ul class="ReactTabs__TabList ReactTabs-list">
    <li class="ReactTabs__Tab ReactTabs-tab is-active">HTML</li>
    <li class="ReactTabs__Tab ReactTabs-tab">React</li>
  </ul>
  ...
```

what I wish to have:
```
<div class="ReactTabs">
  <ul class="ReactTabs-list">
    <li class="ReactTabs-tab is-active">HTML</li>
    <li class="ReactTabs-tab">React</li>
  </ul>
  ...
```

So the question is: Do I need the default classes for functional purpose?
Or would it be possible to change the className behaviour?

For example change: 
https://github.com/reactjs/react-tabs/blob/master/src/components/Tab.js#L67
```
className={cx(
  'ReactTabs__Tab',
  className,
  {
    [activeTabClassName]: selected,
    [disabledTabClassName]: disabled,
  }
)}
```
to: 
```
className={cx(
  className,
  {
    'ReactTabs__Tab': !className,
    [activeTabClassName]: selected,
    [disabledTabClassName]: disabled,
  }
)}
```

**Comment by alexanderwallin** [comment]
Seeing there is a `Tabs.setUseDefaultStyles(bool)`, it would make sense to have `Tabs.setUseDefaultClassNames(bool)`. You could submit a PR, although I'm not sure how fast it will be addressed.

**Comment by danez** [comment]
react-tabs 1.0.0 does replace the default class names instead of extend them.

**Comment by abderrahmane-tj** [comment]
What about when one is using the default css, and does not want to replace the default classNames, and only wants to add a new className to the existing ones ?

imho instead of making the component replace the classes by default, there should be a special boolean prop that controls how className prop behaves.

**Comment by stahlmanDesign** [comment]
@abderrahmane-tj I would also like to extend the className instead of replace it. Did you figure out how?

**Comment by joepvl** [comment]
@abderrahmane-tj @stahlmanDesign you could either add the classnames you want to keep by hand (e.g. write `'react-tabs__tab-list your-class'` instead of just `'your-class'`), or you could copy the default styles to your own styles to achieve the desired effect in some other way.

IMO adding a boolean prop for this isn't worth the tradeoff of adding to the complexity of the API.

**Comment by abderrahmane-tj** [comment]
@joepvl `react-tabs__tab-list` is a className owned by the vendor, the consumer shouldn't have to dig in the code to figure out the className to use, and then try extend it manually, that just defeats the purpose of re-usability.
Suppose the owner of this package decides to tweak the CSS a little and changes the structure of the styles, any application that would have used the vendor's className would break.
I understand that the styles used on this package were merely there for so as to have a minimal visual representation of what the package does, and it was not planned as feature by itself. But some of us do like it, and don't really wish to make our own styles, we only want to augment.
Adding a prop that handles how className behaves, caters to those who are not planning on doing the styles from scratch and I think it is a valid reason to make it work that way.
