### ISSUE TITLE
Close TabPanel if Tab is click one more time

### ISSUE THREAD

**Issue by lauterry** [reactjs/react-tabs#158]
Hi

I have an use case where I need to close the TabPanel if I click on the corresponding Tab is clicked a second time.

When I click a the Tab a second time, the `onSelect` callback is not triggered.

How can I performed that please ?

Best regards

**Comment by alexanderwallin** [comment]
I think you can add an `onClick` prop to your `<Tab>` elements, and then update the `selectedIndex` prop on `<Tabs>`.

Give it a try!

**Comment by alexanderwallin** [comment]
I saw now that this issue is 20 days old. Have you solved it yet, @lauterry? If so, please close the issue, and best of all share your solution! :)

**Comment by lauterry** [comment]
Hi @alexanderwallin 

I have implemented exactly what you have suggested : 

```
<Tab					
   onClick={ () => {
       this.handleSelect(0);
   } }>
</Tab>
```

```
handleSelect(index) {
    this.setState({
	selectedTab: this.state.selectedTab === index ? 4 : index
    });
}
```

In order to close the opened tab, this.state.selectedTab must not be equal to an index of an existing tab.

In my example, if you have 3 tabs, in order to close a tab, you can set the value of this.state.selectedTab to 4

Best regards

**Comment by aparij** [comment]
To future proof the solution, you can send -1 instead of some number which can become a valid index if you add extra tabs.

**Comment by lauterry** [comment]
@aparij You're right !
