### ISSUE TITLE
React.createClass deprecated

### ISSUE THREAD

**Issue by meandavejustice** [reactjs/react-tabs#160]
>Warning: Tab: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by philwhln** [comment]
@meandavejustice You beat me too it! :) Just realized we need this as well if we're to continue using `react-tabs`.

**Comment by danez** [comment]
Fixed with 0.8.3
