### ISSUE TITLE
Prep for React v16 and removal for deprecation warnings (PropTypes & createClass)

### ISSUE THREAD

**Issue by padsbanger** [reactjs/react-tabs#167]
Are there any plans to prepare for React v16 as per this post: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

It means replacing all React.PropTypes and using the prop-types package, and replacing all React.createClass using the create-react-class package.

Doing this will also remove the deprecation warnings for anyone using React v15.5.0 which show in the console in development env.

**Comment by danez** [comment]
This was already done in the latest version some days ago.
