### ISSUE TITLE
A new TabPanel is created at each tab switch?

### ISSUE THREAD

**Issue by herve-g** [reactjs/react-tabs#170]
Hi

Everytime you switch from one tab to another, a new TabPanel (and its components) is created. Why create a new object everytime? It makes difficult to retain states of the TabPanel components when the user switches tabs. It would be better to keep the same TabPanel and re-render it instead of creating a new one.

Am I missing something?

Thank you.

**Comment by joepvl** [comment]
Once you upgrade to version `1.0.0` (not released yet, but will be soon), see https://github.com/reactjs/react-tabs#forcerender-boolean

For the moment, you can use the `forceRenderTabPanel` prop on the `<Tabs>` component for this purpose; set it to `true` and your tabs will all be rendered to the DOM (and hiding/showing is controlled via CSS). Note that this is actually in the docs, it's just not very obvious ;).

**Comment by danez** [comment]
With 1.0.0 now you can do both versions:
* use the `forceRenderTabPanel` prop on the `<Tabs>` component, to render all tabs to the dom even if hidden.
* use the `forceRender` prop on individual `<TabPanel>` components, if you only want certain tab panels to be always rendered.
