### ISSUE TITLE
PropTypes validation

### ISSUE THREAD

**Issue by JuliusPopoola** [reactjs/react-tabs#171]
Warning: Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types Check the render method of `Tabs`.

Above the error message that I currently get using the NPM 0.8.3 version or react-tabs with react 15.0.2.

**Comment by danez** [comment]
Are you doing something special with the proptypes of react-tabs? Do you have an example?
I cannot reproduce this currently.

**Comment by JuliusPopoola** [comment]
<div>	      
    <Tabs onSelect={handleSelect}>
        <TabList>
          <Tab> Menu</Tab>
          <Tab>Search</Tab>
        </TabList>
        
        <TabPanel>
                <MenuPanel />
        </TabPanel>
        <TabPanel>
               <SearchPanel />
        </TabPanel>
        </Tabs>
    </div>

**Comment by danez** [comment]
This is a problem with the combination of react-version your are using.
We updated the code to work with react 15.5, but unfortunately this makes react version < 15.3 or <14.9 print this warning.

https://github.com/reactjs/prop-types/blob/master/README.md#compatibility

So either you update react to at least 15.3 or fix the version of react-tabs to 0.8.2.
