### ISSUE TITLE
Warning: Unknown prop `tabId` on <div> tag

### ISSUE THREAD

**Issue by fabriciofrontarolli** [reactjs/react-tabs#174]
I have upgraded my app to use the new version of React 15.5, now it's throwing error logs.

Warning below
-------------------------------------------------

warning.js:36 Warning: Unknown prop `tabId` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Tabs)
    in div (created by Tabs)

-------------------------------------------------

I believe that by using the prefix "data" would solve the issue.
source: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by danez** [comment]
Which version of react-tabs do you have installed?
Can you provide an example with which I can reproduce this?

By looking at the code this should not happen unless you do something like this, which is not valid.
```
<Tabs tabId="1">
...
```
