### ISSUE TITLE
selectedClassName not working on the main component or setting underneath

### ISSUE THREAD

**Issue by DClark5218** [reactjs/react-tabs#176]
```<Tab className="tab" selectedTabClassName="select-tab">My Tab</Tab>```

Desired effect is to override component selected class, but it doesn't seem to work for me.

Thanks!

**Comment by joepvl** [comment]
This prop is only available on the `<Tabs>` component. You can only set it for all tabs at once. Also, be advised that in versions before `1.0.0`, the equivalent prop is called `activeTabClassName` and should be passed into `<TabList>`.

**Comment by danez** [comment]
Yes @joepvl is correct about version 1.0.0. You either set `selectedTabClassName` on `<Tabs />` or `selectedClassName` on `<Tab />`, where the former will overwrite the later one if used together.

**Comment by DClark5218** [comment]
@joepvl, @danez  Thanks guys! Seems like yarn install loaded a couple of versions back.
