### ISSUE TITLE
Checksum invalid error when using serverside rendering

### ISSUE THREAD

**Issue by webeli** [reactjs/react-tabs#177]
Seen other issues on this but all are closed. Is this really fixed?

**Getting this error message:** 
React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) tab" id="react-tabs-0" aria-selected="tr
 (server) tab" id="react-tabs-16" aria-selected="t_

Using the latest version: react-tabs@0.8.3
Typescript types: @types/react-tabs@^0.5.22"

![image](https://cloud.githubusercontent.com/assets/3446889/25796734/0e749540-33db-11e7-9eb5-3ae0d6692017.png)

**Comment by danez** [comment]
This is already fixed in 1.0.0-alpha.2

Documentation is not written yet, but you have to reset the id-counter in your ssr.

```
import { resetIdCounter } from 'react-tabs';
...
resetIdCounter();
render();
...
```
