### ISSUE TITLE
lack of documentation

### ISSUE THREAD

**Issue by degr** [reactjs/react-tabs#181]
Hello, can you please update documentation about properties, that your components can receive? I was need to disable tabs, and to do it I need to read component code. Fortunately I found pack of undocumented properties, such as

``` ['selected', 'disabled', 'panelId', 'activeTabClassName', 'disabledTabClassName', 'className', 'children', 'id']```

**Comment by danez** [comment]
They are all documented in the README.

**Comment by degr** [comment]
there is nothing > https://github.com/reactjs/react-tabs/blob/master/README.md

Can you share a link?

**Comment by danez** [comment]
Yes in there are all props described

**Comment by degr** [comment]
Man, you are kidding me? Try to search "panelId", there is no one substring in readme.

**Comment by danez** [comment]
`panelId` is a private prop that is only meant to be used internally.

**Comment by degr** [comment]
ok, disabled is provate too?

**Comment by danez** [comment]
No, but you are right this one is missing in the Readme. Sorry
