### ISSUE TITLE
@types outdated

### ISSUE THREAD

**Issue by Jermorin** [reactjs/react-tabs#182]
Hi guys ! 

I'm using this lib with typescript in my projet, my compilator/ide is so sad :) 

I'm refering to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/react-tabs/index.d.ts and i''ve noticed that the interfaces are outdated. 

For example : Prop selectedTabClassName of `<Tabs></Tabs>` is unknown. 

What is the recommended workflow to fix this issue ? 

Perhaps I can join forces with you !

Thanks,

**Comment by humphries40** [comment]
So I'm in the same situation as you, just decided to use this tool and we're using typescript. 

From what I've seen other places I believe that the correct workflow is creating a pull request on the DefinitelyTyped repo with the updates. Similiar to this one (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8805).
