### ISSUE TITLE
Enable component composition instead of relying on using directly the components provided

### ISSUE THREAD

**Issue by Magellol** [reactjs/react-tabs#187]
Hey guys,

I was trying to get around a simple use case and discovered I couldn't do it very easily.
Let's say that I want to provide some abstraction around the `<Tab />` component, such as

```javascript
import { Tabs, Tab, ... } from 'react-tabs';

const SomeOtherTab = props => (
  <Tab className={styles.myTabStyle} {...props} />
);

render() {
  <Tabs>
    <TabList className={styles.tabList}>
        <SomeOtherTab>Tab 1</SomeOtherTab>
        <SomeOtherTab>Tab 2</SomeOtherTab>
    </TabList>

    <TabPanel>
      Content One
    </TabPanel>
    <TabPanel>
      Content Two
    </TabPanel>
  </Tabs>
}
```

This won't let me do it. I think there are some legit use case where you want to compose some other components with one of provided ones. I first get a proptype warning ([here](https://github.com/reactjs/react-tabs/blob/master/src/helpers/propTypes.js#L41)), then the tabs don't seem to work at all.

Any suggestions?

**Comment by kenan2002** [comment]
Any progress on this? I'm trying to export my own version of Tab which accepts extra props to satisfy my business requirements when I come across this issue. I tried to hack around but found no way to workaround.
Any suggestion to work aorund this?

**Comment by leanne1** [comment]
I would also really like to see this. I am having a similar issue. I need to wrap `TabList` in a higher-order component to give some additional functionality and it causes the`childrenPropType` check to fail and generates [the same warning](https://github.com/reactjs/react-tabs/blob/master/src/helpers/propTypes.js#L41). In my case everything still works correctly, but i don't want a false warning getting logged.

**Comment by danez** [comment]
This is possible since 2.0.0. You can now do:

```diff
import { Tabs, Tab, ... } from 'react-tabs';

const SomeOtherTab = props => (
  <Tab className={styles.myTabStyle} {...props} />
);
+ SomeOtherTab.tabsRole = Tab.tabsRole;

render() {
  <Tabs>
    <TabList className={styles.tabList}>
        <SomeOtherTab>Tab 1</SomeOtherTab>
        <SomeOtherTab>Tab 2</SomeOtherTab>
    </TabList>

    <TabPanel>
      Content One
    </TabPanel>
    <TabPanel>
      Content Two
    </TabPanel>
  </Tabs>
}
```
