### ISSUE TITLE
Styling is not getting applied

### ISSUE THREAD

**Issue by veris-amoghbanta** [reactjs/react-tabs#189]
This is how the example looks in my case :

<img width="252" alt="screen shot 2017-06-30 at 1 34 12 pm" src="https://user-images.githubusercontent.com/16878180/27726663-f07f2dec-5d98-11e7-9737-76b599c21cca.png">

P.S. I am using react-native-web to transpile, but that should not be an issue.
react version is : 15.6.1

**Comment by KamilKmitaLasoft** [comment]
Is it work on react 15.6 ?

**Comment by KamilKmitaLasoft** [comment]
Does it work on react 15.6 ?

**Comment by veris-amoghbanta** [comment]
yes it does!

**Comment by gabsschneider** [comment]
I am having this same issue using react ˆ16.4.0 and react-tabs ˆ2.2.2

Any idea why this is happening?

**Comment by joepvl** [comment]
@gabsschneider just to make sure... did you include the included default stylesheet, [like the readme instructs](https://github.com/reactjs/react-tabs#styling)?
