### ISSUE TITLE
Move index.d.ts from DefinitelyTyped to this repository

### ISSUE THREAD

**Issue by sgronblo** [reactjs/react-tabs#192]
Just curious why more package maintainers don't do this. Especially if the same committers are involved with both the index.d.ts file in DT and the original package?

**Comment by danez** [comment]
I don't know how typescript definition files work, if they can be in this repo then we should do it.

Would you mind creating a PR?

**Comment by sgronblo** [comment]
@danez I was under the impression that you had been involved with the type definitions in DT as mentioned here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-tabs/index.d.ts#L3

**Comment by danez** [comment]
Yes, but I do not know what needs to be done in order for typescript to pickup this files from here? just create index.d.ts next to index.js? Or does package.json need to be adapted, so that typescript finds it?

**Comment by sgronblo** [comment]
I think you add the index.d.ts file to the repository and then add a field to the package.json file. I think it was called `typings` or something like that. There might have been some default functionality that picks it up automatically if it's named index.d.ts as well.

**Comment by sgronblo** [comment]
I think this page describes the process: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by sgronblo** [comment]
I was having trouble using react-tabs in TS since the DT definitions don't seem to be properly constructed.

For example it is not possible to do something like:

```
<Tab onClick={() => undefined} />
```

This seems to be due to `Tab` being defined as `interface Tab extends React.ComponentClass<TabProps> {}`

I tried checking out the DT repository and tried to improve the types a bit and getting rid of some stuff that seemed redundant. However, I got stuck when I noticed that some of the property names in for example `TabsProps` are the same as properties in React's `HTMLAttributes` but with a different type. For example, className and onSelect.

Currently I don't think TS has support for this case, which leaves two options.

1. Making a breaking change to this repository that renames `onSelect` and `className` of `Tabs` and anything else that clashes with basic HTML attributes.
2. Forking this library to do 1.

**Comment by sgronblo** [comment]
I ended up ditching react-tabs for the feature I was implementing. The trouble with the types was part of the problem, but the bigger issue was that I was making a responsive layout that had one TabList that was shown for a certain breakpoint and another TabList for another breakpoint, which was not supported out of the box by react-tabs. So I just created a similar homebrew solution. I still think you should at least consider whether in the future it makes sense to not define props that clash with HTML props if you are planning on passing them over to the underlying element.

**Comment by danez** [comment]
Done
