### ISSUE TITLE
Tabs are not defined - error message

### ISSUE THREAD

**Issue by elbsurfer** [reactjs/react-tabs#199]
Hello,
currently I want to test some things without using webpack or another compiler.

Therefore I created a html page which looks like this:

```
<div class="container">
	<div id="container"></div>
</div>

<script src="https://fb.me/react-15.1.0.js"></script>
<script src="https://fb.me/react-dom-15.1.0.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
<script src="_resources/react-tabs.min.js"></script>
<script type="text/babel" src="_resources/app.js"></script>
```

My app.js looks like this:

```
const Title = () => {
    return (
        <div>
            <div>
                <h1>Log</h1>
            </div>
        </div>
    );
}


class MyLog extends React.Component{
	constructor(props){
	    // Pass props to parent class
	    super(props);
	    // Set initial state
	    this.state = {
	        data: [],
	        shops: [],
	    }
	}

	render(){
	        // Render JSX
	        return (
	            <div>
	                <Title />
	                <Tabs>
	                    <TabList>
	                        <Tab>Title 1</Tab>
	                        <Tab>Title 2</Tab>
	                    </TabList>
	                    <TabPanel></TabPanel>
	                    <TabPanel></TabPanel>
	                </Tabs>

	            </div>
	        );
	    }
}
ReactDOM.render(<MyLog />, document.getElementById('container'));
```
But when I start this small app, I get the message: **Uncaught ReferenceError: Tabs is not defined**

Why is this the case, am I missing something? Thanks for helping me!

**Comment by danez** [comment]
In the bundled build the component is called `ReactTabs`
so it would look like this:

```
 <ReactTabs.Tabs>
	                    <ReactTabs.TabList>
	                        <ReactTabs.Tab>Title 1</ReactTabs.Tab>
	                        <ReactTabs.Tab>Title 2</ReactTabs.Tab>
	                    </ReactTabs.TabList>
	                    <ReactTabs.TabPanel></ReactTabs.TabPanel>
	                    <ReactTabs.TabPanel></ReactTabs.TabPanel>
	                </ReactTabs.Tabs>
```

**Comment by elbsurfer** [comment]
@danez 

Thanks for the quick reaction. I did this, and now I get this error:

`Uncaught TypeError: (0 , b.default) is not a function`

-> http://d.pr/i/FKLe1t

Does this tells you something? ;-)

**Comment by danez** [comment]
I think you are missing the classnames dependency. 
https://unpkg.com/classnames@2.2.5

You might also want to use the non minified version at first, then the errors should be more clear.

Basically the requirements are:
react
react-dom
classnames
prop-types

**Comment by elbsurfer** [comment]
@danez 

I do the following now:
<body>
    <div class="container">
        <div id="container"></div>
    </div>

    <script src="https://fb.me/react-15.1.0.js"></script>
    <script src="https://fb.me/react-dom-15.1.0.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
    <script src="https://unpkg.com/classnames@2.2.5"></script>
    <script src="https://unpkg.com/prop-types/prop-types.js"></script>
    <script src="_resources/react-tabs.js"></script>
    <script type="text/babel" src="_resources/app.js"></script>
</body>

And I get the following error: http://d.pr/i/qa5om0

app.js shows me just this: http://d.pr/i/Eu8iU0

What am I missing here? Do I not only include the react-tabs.js, but do I need to somehow initialize it in my app.js as well?

P.S: Is it always so complicated to get a development version of react running? ;-)

**Comment by danez** [comment]
If you are still interested in version 2.1.0 the umd build has been fixed and I added examples on how to use it: https://github.com/reactjs/react-tabs#installing
