### ISSUE TITLE
Consider to make the tabpanels focusable

### ISSUE THREAD

**Issue by afercia** [reactjs/react-tabs#206]
It would be great to consider to make the tabpanels focusable adding `tabindex="0"`. While the ARIA Authoring Practices don't require the tabpanels to be focusable, they state tabpanels can be made focusable:

https://www.w3.org/TR/wai-aria-practices/#tabpanel
Pressing the Tab key:
> When the tab list contains the focus, moves focus to the next element in the page tab sequence outside the tablist, which is typically **either the first focusable element inside the tab panel or the tab panel itself**.

This is even more clear in the 2 linked examples, e.g.:
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

On the example page, see the table that lists the attributes used in the example:
tabpanel > tabindex=0

- Puts the tabpanel in the page Tab sequence.
- Facilitates movement to panel content for assistive technology users.
- Especially helpful if there are panels that do not contain a focusable element.

This is particularly important because the tabpanels use `aria-labelledby`. Some of the major screen readers have a different interaction model. VoiceOver on Safari announces the `aria-labelledby` even when arrowing through the content with Control-Option-Right (or Left) arrow.

Instead, to actually use the tabs with JAWS and NVDA on Windows, there's the need to switch to "forms mode" (both screen readers tend to do that automatically). In forms mode, navigation with arrow keys doesn't work. Only the Tab key works, thus the tabpanels need to be focusable to make `aria-labelledby` announced.

As mentioned in the example, this also greatly helps to move focus to the active tab panel content without "skipping" any content. Also, since a generic component can't predict what type of content will be used within the tabpanels, making them focusable is probably the best option.

As far as I see, this would be as simple as adding `tabindex="0"` to _all_ the tabpanels regardless of which is the active one: it won't do anything on the tabpanels hidden with `display: none`.

**Comment by danez** [comment]
There is also an open PR for this which tries to integrate this in a non breaking manner. #204

**Comment by afercia** [comment]
@danez thanks. I've also realized (I'm slow) that `tabindex="0"` can be passed to the `TabPanel` component during implementation.

**Comment by afercia** [comment]
@danez #204 is different, it tries to set tabindex to the tabs in the tablist. That goes against the expected interaction model, as mentioned there.

Instead, this is about setting a tabindex 0 on the tab panels.

**Comment by danez** [comment]
Thanks for the clarification. I think changing the default to always set tabindex=0 on the TabPanel is not a good idea, because then you are also able to focus the panel when clicking with the mouse inside the TabPanel.

And as you noticed yourself you can already create this behaviour by supplying tabIndex to the TabPanel. Is that good enough?

**Comment by afercia** [comment]
@danez  yes thanks I just realized to late that this was so easy to do in the passed content :) and that's how we implemented it. Agree that it really depends on the nature off the content so making this the default wouldn't be ideal.
