### ISSUE TITLE
I use onClick event in tab but all the tab call the function ..

### ISSUE THREAD

**Issue by nuruddinXbadawi** [reactjs/react-tabs#207]
I use more way to call a function when clicking on the tab but all tab is called the function on the first load... why ?

![screen shot 2017-09-23 at 10 00 03 am](https://user-images.githubusercontent.com/5736522/30770959-024a9814-a046-11e7-8ca9-251a1ac2f45b.png)

Log: 

![screen shot 2017-09-23 at 9 57 37 am](https://user-images.githubusercontent.com/5736522/30770946-b8109348-a045-11e7-8a01-374baa21201d.png)

**Comment by joepvl** [comment]
Unless you have `this.fetchData` returning a function based on the string passed, this is not a problem with this package, or even React for that matter. You are calling that function on the spot, passing it a string (`'files'`, for example), and passing the result to the `onClick` prop. Hence, the first time the component renders (React calls its `render` method), `this.fetchData` is called 3 times with different strings, whatever it returns is assigned to the `onClick` props, and you get the resulting logs. If I'm right about this assumption, you can probably achieve the desired behaviour by wrapping the call in a function, something like this:

```jsx
<div onClick={() => this.fetchData('files')}>
```
You can read more about this in the React docs under "Handling Events": https://facebook.github.io/react/docs/handling-events.html.

However, like that docs page says all the way at the bottom, beware that now you are creating a new function to pass to `onClick` every time the component rerenders (that is, every time React calls its `render` method)! This may in turn cause the `<Tab>` to rerender unnecessarily. There is a number of ways you could refactor this, for example by creating separate `onClick` instance methods for each tab (e.g. `onTopicsClick`, `onFilesClick`, `onSubsitesClick`), and handling the specific clicks in there -- at the risk of having some code duplication. Or you could create a _higher order_ method to indeed return a function based on the string you pass it, and cache the functions you create so you don't create new ones on every render. Something like:

```js
export class YourComponentName extends Component {
  constructor(props) {
    super(props);
    // ...
    this.fetcherCache = {};
    this.getFetcher = this.getFetcher.bind(this);
    // ...
  }
  // ...
  getFetcher(dataType) {
    if (!this.fetcherCache[dataType]) {
      this.fetcherCache[dataType] = () => this.fetchData(dataType);
    }
    return this.fetcherCache[dataType];
  }
  // ...
  render() {
    // ...
    <Tab onClick={this.getFetcher('string')}>...</Tab>
    // ...
  }
}
```
