### ISSUE TITLE
Tablist and tabpanel have to be in same component?

### ISSUE THREAD

**Issue by jpancake** [reactjs/react-tabs#208]
is it possible to have Tablist in one and the tab panels in another component? I currently have this setup and my page is blank.

**Comment by danez** [comment]
This is not supported. sorry.

**Comment by mkarajohn** [comment]
I faced the same issue. 

@danez My usecase, and I suppose @jpancake 's too, is probably separation of code. 

In my case, I need to have a modal which has a top level tabbing interface and some TabPanels need to have their own nested tabbed interfaces. I use CSS modules, and breaking up big structures into smaller components helps.

**Comment by jpancake** [comment]
Yes, mostly separation of code, I like my components to be reasonably sized. I was trying to put tabs and tablist in a higher order component.

**Comment by olwen1987** [comment]
Even i have the same issue. I tried to create the tabs dynamically but now the select event is not being fired

**Comment by mkarajohn** [comment]
@olwen1987 @jpancake 

Since this seems to be an active post, I will tel you how I came around this. What I did is to use simple functions to return the elements. 

So, instead of having something like

```
    <Tabs>
      <TabsContainer />
      <PanelsContainer />
    </Tabs>
```

where

```
// TabsContainer.jsx
function TabsContainer(props) {
  return (
    <TabList>
      <Tab>...</Tab>
      <Tab>...</Tab>
      <Tab>...</Tab>
    </TabList>
  )
}

```

and 

```
PanelsContainer.jsx
function PanelsContainer(props) {
  return (
    [
      <TabPanel key="...">// ...</TabPanel>
      <TabPanel key="...">// ...</TabPanel>
      <TabPanel key="...">// ...</TabPanel>
    ]
  );
}
```

I do this instead: 

```
    <Tabs>
      {renderTabs(props)}
      {renderPanels(props)}
    </Tabs>
```

```
// renderTabs.jsx
function renderTabs(props) {
  return (
    <TabList>
      <Tab>...</Tab>
      <Tab>...</Tab>
      <Tab>...</Tab>
    </TabList>
  )
}
```

```
renderPanels.jsx
function renderPanels(props) {
  return (
    [
      <TabPanel key="...">// ...</TabPanel>
      <TabPanel key="...">// ...</TabPanel>
      <TabPanel key="...">// ...</TabPanel>
    ]
  );
}
```

By not using JSX syntax, I am not creating new React elements of types `TabsContainer` and `PanelsContainer` that the `Tabs` component will see and throw on me, because it is expecting children of type `TabList` and `TabPanel`

**Comment by olwen1987** [comment]
@mkarajohn Let me try your solution. I was seeing that the tab selections events are not propogated whenever there is a react component between tabs and tabs list. I think your solution should suffice. Thanks. Will update if that worked

**Comment by samplefrequency** [comment]
Looks like this is still hanging around. Like others here, I agree that it would be nice to be able to render the TabPanels in a separate component. Has anyone else had any luck?

**Comment by mkarajohn** [comment]
@samplefrequency check my proposed solution from a couple of posts above, it may be enough to resolve your issue

**Comment by danielitorb** [comment]
@mkarajohn can you show me the complete example? please

**Comment by mkarajohn** [comment]
@danielitorb See https://github.com/reactjs/react-tabs/issues/208#issuecomment-348495796 . 
I think it should be enough to give you a general gist :)

**Comment by falcononrails** [comment]
@mkarajohn I tried your solution and it worked. 
I'm using Typescript, so here's a basic gist to make it work:

Your separate component:
**CustomTabs.tsx**
```ts
Interface Props {}
export default ({}) => (
<TabList>
    <Tab>...</Tab>
    <Tab>...</Tab>
    <Tab>...</Tab>
</TabList>
)
```
In your main component:
```ts
<Tabs>
   {CustomTabs({})}   
</Tabs>
```
Works like a charm!

**Comment by mkarajohn** [comment]
@falcononrails glad I could help, even 3 years later! :smile:
