### ISSUE TITLE
Prebuilt versions in /dist are broken

### ISSUE THREAD

**Issue by joepvl** [reactjs/react-tabs#209]
See title. I might be missing someting but it seems those dist files should all Just Work™, the only requirement being that `React` and `ReactDOM` are included on the page. The minified version does load, but it gives a cryptic error in the console when rendering any of the components. The unminified version throws an error when merely using a component. You can find an example here: https://codepen.io/joep/pen/oGWxJm. You'll have to open your browser console to see the errors, as Codepen's built in one doesn't show them.

I guess priority on this issue shouldn't be super high, as it seems this has been broken for a while (since 1.0.0, actually) and no one seems to have complained since. ;)

---
P.S. If you've come here in search of a way to test `react-tabs` directly in your browser, try a tool like [codesandbox.io](https://codesandbox.io) or [webpackbin.com](https://www.webpackbin.com). 
Here's a CodeSandbox example: https://codesandbox.io/s/3x010xpw8m.

**Comment by danez** [comment]
This is fixed in the latest version see https://github.com/reactjs/react-tabs#installing

**Comment by joepvl** [comment]
I noticed, awesome! Although it seems only the production version is working at the moment, the development version will throw with `react-tabs.development.js:689 Uncaught TypeError: Cannot read property 'oneOfType' of undefined` because PropTypes is not included in the build. 😅

**Comment by danez** [comment]
It is mentioned in the Readme and in the examples

**Comment by joepvl** [comment]
Aww yeah, missed that! Apologies. And thanks again for all the work you put in. 👍
