### ISSUE TITLE
Programmatically Focus Tab Component

### ISSUE THREAD

**Issue by sepehr500** [reactjs/react-tabs#214]
Is there a way to programatically  focus the `<li>` element in the `<Tab />` component.  When using the arrow keys to switch tabs in uncontrolled mode, the tab will switch but focus will be lost. Is there a way to set the focus in the `onSelect` callback?

**Comment by danez** [comment]
Do you have an example? Imho the focus should stay after switching, no matter if controlled/uncontrolled. Which browser are you seeing this?

**Comment by sepehr500** [comment]
I am using the latest version of chrome. In uncontrolled mode the tab focus does not change when using the arrow keys.

**Comment by joepvl** [comment]
Might this have something to do with 00a8401, which was included in v2.1.0?

**Comment by sepehr500** [comment]
I had meant to say controlled mode. The focus does not change in controlled mode.

**Comment by joepvl** [comment]
I updated [the pen](https://codepen.io/joep/pen/ZXoaxP) to use controlled mode for the top level tabs, and see no change in focus behaviour. It even switches seamlessly between controlled top level tabs and uncontrolled nested ones using the `tab` key.

Note: I am aware this behaviour used to be broken before 1.0.0 was released. Are you sure you're using an up-to-date version?

**Comment by sepehr500** [comment]
I am on the newest version. I will look into it more to see why it is not working...but it works in uncontrolled mode.

**Comment by bragi92** [comment]
I'm also facing a similar issue with "react-tabs": "2.2.1" in Chrome + Edge + Firefox.
It works like a charm with uncontrolled mode but its failing for controlled mode.

**Comment by bragi92** [comment]
Upgrading to 3.0.0 fixes the issue for me.
