### ISSUE TITLE
Tabs do not get rendered

### ISSUE THREAD

**Issue by abhaychitnis** [reactjs/react-tabs#216]
I am getting started with ReactJS. I am trying to get the basic React-Tabs example to work. My TabComponent looks like this. 

```
import React from 'react';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';

export default () => (
   <Tabs>
    <TabList>
      <Tab>Title 1</Tab>
      <Tab>Title 2</Tab>
    </TabList>
 
    <TabPanel>
      <h2>Any content 1</h2>
    </TabPanel>
    <TabPanel>
      <h2>Any content 2</h2>
    </TabPanel>
  </Tabs>
);
```
However this does not render Tabs. The result looks as follows 

![image](https://user-images.githubusercontent.com/28629632/31334001-e0dba29c-ad09-11e7-99b3-fd678b5379ab.png)

Clearly I am missing out somethings basic. Please let me know what is missing.

I am using versions react 16.0.0, react-tabs 2.1.0

**Comment by danez** [comment]
You are missing the styles for the tabs, the content is all rendered afaics.
https://github.com/reactjs/react-tabs#styling

**Comment by abhaychitnis** [comment]
Yup. That worked.
