### ISSUE TITLE
I can't link to a tab from another tab.

### ISSUE THREAD

**Issue by beckbeach** [reactjs/react-tabs#219]
Hi!  I can't link to another tab when I am on a different tab. For example, I have a link to click to the next tab but it won't work. Sometimes, an id of react-tab-2 will come up for tab 2 and sometimes it will be react-tab-10 or a different number. When I make a link of <a href="#react-tab-2">Click to next tab</a> , it won't work. Is this possible to do?

**Comment by danez** [comment]
Sorry for the late reply. What is the desired outcome when clicking on the link? Do you want to open the tab or just scroll to the tab?

**Comment by joepvl** [comment]
I'm closing this issue because it has been inactive for over 6 months and there is not much to add to the answer @danez provided.
