### ISSUE TITLE
why build:umd use rollup but not use babel

### ISSUE THREAD

**Issue by wangning0** [reactjs/react-tabs#224]
First, thank you very much for the react-tabs project, it's very well . but when I was reading the source code , I have some doubts about the content of npm sctipts.

  In the code, when you build the project, you choose two tools ,babel and rollup.  **when build the project to umd ,you use rollup**.   **esm and commonjs use babel** . As i know babel can too. so I hava no idea why doing this , if you have time ,would you mind helping me to solve these doubts.

At last , because I'm not a native speaker , forgive my pool english. Thx!

**Comment by danez** [comment]
Babel transforms es2015+ to es5. 
Rollup bundles all files into one single file.

We use babel also for UMD with the rollup-babel-plugin, but babel alone cannot create an UMD bundle.
I could use rollup for all cases, but it works right now and probably does not improve anything.

**Comment by wangning0** [comment]
Thx!
