### ISSUE TITLE
Link to examples in README returns 404 page

### ISSUE THREAD

**Issue by kkaczmarczyk** [reactjs/react-tabs#226]
Link to examples in README returns 404 page

[examples/umd](https://github.com/reactjs/react-tabs/blob/HEAD/examples/umd/) link return 404 in Github.

**Comment by dominhhai610** [comment]
@kkaczmarczyk this file you are requesting is not exist in source

**Comment by kkaczmarczyk** [comment]
Yeah that's the point - so why is it linked in README?

**Comment by haianhnc** [comment]
@kkaczmarczyk
The example was move to old/examples folder. I just changed the link to old_folder at this PR
https://github.com/reactjs/react-tabs/pull/241
