### ISSUE TITLE
Stopping event propagation

### ISSUE THREAD

**Issue by abhishekjakhar** [reactjs/react-tabs#243]
When we click on the Tab the event propagates to the top of DOM and cause side effects in the program so is there any way to stop event propagation and stop event bubbling when clicking on the tab ?

**Comment by danez** [comment]
The onSelect callback receives the event that triggered the select, so I guess you could stop the propagation there. Would that work for your case?

**Comment by yoonwaiyan** [comment]
@abhishekjakhar did you solved this issue? I've applied `preventDefault` but my page is being scrolled to the top.

**Comment by abhishekjakhar** [comment]
@yoonwaiyan I don't even remember what Issue I was facing back then

**Comment by SereiaMaster** [comment]
Somebodyresolve this issue?
