### ISSUE TITLE
Trigger Tab Switch Via Button Element

### ISSUE THREAD

**Issue by harlemfitzgerald** [reactjs/react-tabs#247]
**First and foremost:** Thanks for such an fab component! This is a newbie life-saver! 

**Second:** How would one go about triggering a change of panels upon clicking a button element at the bottom of the panel? Ex. http://app.happyendin.gs/review (Edit tab)

**Comment by joepvl** [comment]
Assuming you're letting the component manage tab selection for you right now, you would need to add some logic to use the component in controlled mode by setting the `selectedIndex` prop on `<Tabs>`, and driving the state that way. This will allow you to change which tab is selected by setting the component's state, which you can then do in response to a button click. Here's a barebones example: https://codesandbox.io/s/x7vp30q474

**Comment by harlemfitzgerald** [comment]
Sweet! Thanks so much for the example! That gives me what I need!
