### ISSUE TITLE
Not working on React 16.4

### ISSUE THREAD

**Issue by camd** [reactjs/react-tabs#248]
Clicking on different tabs isn't working.  Just stays on the default tab I'd set.  I'm controlling the selected tab with state.  I can see that my state is changing, though.

**Comment by joepvl** [comment]
As stated in the readme, `defaultIndex` doesn't work in conjunction with `selectedIndex`. Use your component's (initial) state to define which tab should be selected by default.

**Comment by camd** [comment]
My apologies, I was too hasty in writing this up.  I don't use ``default``.  I just meant the initial state value for ``selectedIndex`` that I set.  My code is:

        <Tabs
          selectedTabClassName="selected-tab"
          selectedIndex={tabIndex}
          onSelect={tabIndex => this.setState({ tabIndex })}
        >

**Comment by joepvl** [comment]
In that example, the value for the `selectedIndex` prop should be `this.state.tabIndex`.

In any case, I wrote a controlled tabs example with `react@16.4.0` and `react-tabs@2.2.2` yesterday (for a different issue), and it works just fine: https://codesandbox.io/s/x7vp30q474.

**Comment by camd** [comment]
Thanks!  I'll take a look at your example and see what I'm doing wrong.

Just for clarity: In my example, at the beginning of my ``render()`` function, I generally deconstruct ``state`` and ``props`` as such: ``const { tabIndex } = this.state;``  Sorry I neglected to include that.

**Comment by camd** [comment]
OK, I found out my issue was some handling I was doing in ``getDerivedStateFromProps`` to determine a default tab index.  The behavior of that function changed a bit in React 16, so that's my problem.  Sorry for the mixup...
