### ISSUE TITLE
onSelect handler return value needs better explanation in the doco

### ISSUE THREAD

**Issue by joe-oli** [reactjs/react-tabs#255]
According to the readme.md:

onSelect: (index: number, lastIndex: number, event: Event) => ?boolean	  
1) The callback can optionally return true to cancel the change to the new tab.

2) Returning true when the change to the new tab should be canceled is also important in controlled mode, as react-tabs still internally handles the focus of the tabs.

For Controlled components, the two statement make no sense and/or need better explanation.

For controlled components, the change is done manually in any case, by setting the new 'selectedIndex', so it is irrelevant whether true or false is returned from the onSelect handler?

**Comment by danez** [comment]
In controlled mode it is still necessary to return true if a change was canceled I think, because we internally have to handle which element is focused for the keyboard navigation to work correctly.

There might be a better way to handle this though not sure.
