### ISSUE TITLE
When using CustomWrapper selectedClassName does not work.

### ISSUE THREAD

**Issue by digitaldesigndj** [reactjs/react-tabs#256]
I have a custom style wrapper on a `<Tab>` called `<TaskTab>`. If you have a custom wrapper, the `selectedClassName` property no longer works. In fact, the custom wrapper element does not update it's class at all.

I've been poring over the docs. I am using `TaskTab.tabsRole = 'Tab';` and the tab behavior works fine, I just can't style the states. Am I missing something?

```
<Tabs>
  <TaskTabList>
    <Tab selectedClassName="active">Title 1</Tab> <- Works fine
    <TaskTab>Title 2</TaskTab> <- Class never updates
  </TaskTabList>
  <TabPanel>
    <h2>Tab Content 1</h2>
  </TabPanel>
  <TabPanel>
    <h2>Tab Content 2</h2>
  </TabPanel>
</Tabs>
```

I am also using the wrapper component with a custom disabled class, and that work fine. Help is greatly appreciated! 😃

**Comment by digitaldesigndj** [comment]
I figured it out shortly after posting. I needed to pass the `selected` property through my custom component to make it work correctly.

```
const TaskTab = ({ children, disabled, selected }) => (
  <Tab
    className="task-tab"
    disabled={disabled}
    selected={selected}
    disabledClassName="inactive"
    selectedClassName="active"
  >
        {children}
  </Tab>
);

TaskTab.tabsRole = 'Tab';
```

**Comment by joepvl** [comment]
Thanks for taking the time to post your own solution, it's much appreciated!

**Comment by joepvl** [comment]
@jpbarela it isn't, however, to make the solution more robust you can spread any passed props you aren't touching onto the wrapped `<Tab>`. I'm not sure how this would affect you in a TypeScript environment, but here's an example adaptation of @digitaldesigndj's solution which allows for flexibility by adding the desired props without overwriting them:

```jsx
import cx from 'classnames';

const TaskTab = ({ className, disabledClassName, selectedClassName, children, ...otherProps }) => (
  <Tab
    className={cx(className, "task-tab")}
    disabledClassName={cx(disabledClassName, "inactive")}
    selectedClassName={cx(selectedClassName, "active")}
    {...otherProps}
  >
    {children}
  </Tab>
);

TaskTab.tabsRole = 'Tab';
```

**Comment by jedrichards** [comment]
Nice detective work. The docs should be updated.
