### ISSUE TITLE
Efficiency 

### ISSUE THREAD

**Issue by JarolinVargas** [reactjs/react-tabs#265]
I'm seeing that in the DOM the content in all inactive tabs is removed and then re-inserted when a specific tab is active. Is this inefficient? Would it be better to set that content for each tab and simply hide/show the right tab without removing and re-inserting the content?

**Comment by rlax** [comment]
You could use [forceRenderTabPanel](https://github.com/reactjs/react-tabs#forcerendertabpanel-boolean) to set tab content without re-inserting, try it out.
