### ISSUE TITLE
The Luigi tab being disabled by default in the demo is upsetting

### ISSUE THREAD

**Issue by kristajg** [reactjs/react-tabs#267]
Why is it always about Mario? Luigi is a good person I assume. Sure my mom still calls him 'Green Mario' but he is a viable Smash Bros character

**Comment by joepvl** [comment]
Fair enough! If you make a pull request to change things up, I don't see why we wouldn't merge it. Personally, I think I would enjoy reading a more elaborate motivation. 😉

**Comment by kristajg** [comment]
@joepvl  You got it!

**Comment by danez** [comment]
Feel free to create PR :)
