### ISSUE TITLE
Support for vertical tabs?

### ISSUE THREAD

**Issue by manavs19** [reactjs/react-tabs#274]
Is it possible to display the tabs vertically?

**Comment by mikkelking** [comment]
That's a cool quick fix, my vote would be for it to be controlled by a prop...  eg `<Tabs vertical>`
Could be an easy PR for someone?

**Comment by mikkelking** [comment]
I have had a couple of interns working on this (and also converting it to use `styled-components` along the way). I'll get them to push their fork and raise a PR for consideration by the community.

**Comment by dylanirlbeck** [comment]
@mikkelking Did we ever get vertical support merged in? Thanks!

**Comment by mikkelking** [comment]
We did get it working, ended up taking the fork into our own project - I'll see if I can bring the code back to the project

**Comment by aounleonardo** [comment]
@mikkelking Any update on the merge?

**Comment by joepvl** [comment]
As shown in the first comment, making the tabs vertical is a matter of styling. This component doesn't care about how it's styled — the default styles are very rudimentary and are mainly included to help people get started quickly. Adding a prop for making the tabs vertical would be going against that philosophy.

**Comment by aounleonardo** [comment]
Makes sense, thanks @joepvl !
