### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'getAttribute' in undefined

### ISSUE THREAD

**Issue by akiryazov** [reactjs/react-tabs#277]
In one case I am getting the following error: 
'Uncaught TypeError: Cannot use 'in' operator to search for 'getAttribute' in undefined'.

I investigated a bit and found that in UncontrolledTabs.js file there is a function which checks if the clicked node is tab (the function is `isTabNode`). The problem comes from the `handleClick` function which is assigning to every node its parentNode until node's parentNode is null. This is the check: 

`while ((node = node.parentNode) !== null)`.

The problem is that when you try to access an object without parentNode it just returns undefined so this check is returning false. Do you think it's better to check not with null but with undefined? 

Thanks!

**Comment by danez** [comment]
Thanks this is fixed in 83f8780d843cdc231e5deb561b456542a2b37a30
