### ISSUE TITLE
Tab & TabPanel key auto assignment

### ISSUE THREAD

**Issue by grmayfie** [reactjs/react-tabs#281]
Hello, 

I'm trying to use react-tabs and give each tab and tabPanel a unique key rather than autoassigning it, and each getting `$` characters inserted into my keys when I do. 

So for example, if I add a tab like: 
``` <Tab key={"tabKey"} tabid={tab.tabId}>{tab.tabName}</Tab>```

then rendered in browser the key for that tab is: 
``` Key : ".$tabKey" ```

What's the proper way to set tab and tabPanel keys manually? Is there a way or is it only controlled by the library?

**Comment by joepvl** [comment]
I don't understand what you're trying to achieve, can you give us a clearer example?

Just to be sure we're on the same page here, `key` is a special prop used internally by React (roughly speaking, it's used to keep track of entities within lists). You can read more about it in the React docs: https://reactjs.org/docs/lists-and-keys.html.
