### ISSUE TITLE
Auto select tab when it is created

### ISSUE THREAD

**Issue by Ericnr** [reactjs/react-tabs#283]
Hey, I'm a newbie programmer and I'm using react-tabs in a little project I'm making. So far I am able to create and destroy tabs as I need to by keeping an array of objects on redux, it looks like this.

![Capturar](https://user-images.githubusercontent.com/43482595/54840261-5d4da900-4cab-11e9-92bc-1c0cfbba42b1.PNG)

But I'm not able yet to automatically switch to the tab Ive just created. Tried looking into react-tabs source code but it is very confusing to me still. Any help is appreciated a lot!

**Comment by Ericnr** [comment]
I got it working

**Comment by dhawaldarji7** [comment]
I'm trying to implement the same functionality. Can you please share how you got this to work?
