### ISSUE TITLE
Tab Component Update Issue

### ISSUE THREAD

**Issue by SBero** [reactjs/react-tabs#285]
I'm having a difficult time trying to figure out why this is occurring...

I have a tab panel with two tabs - Tab A and Tab B.

If I edit a row of data in Tab A using a Slideout, the data in the state is updated, however the Tab A data doesn't show the update. It isn't until I toggle Tab B and go back to Tab A does it show the correct data.

Thoughts?

**Comment by moussaab-moulim** [comment]
hello @SBero 
i am having the same problem did you figure it out yet

**Comment by SBero** [comment]
@moussaab-moulim I never found a good solution other than to set the tab contents to null and then re-make it.

**Comment by joepvl** [comment]
Hi @SBero and @moussaab-moulim, can you help me understand the issue you're having? Without a code sample it's hard to tell exactly what the problem is. If you can provide a sample that reproduces the problem I can help you figure it out.
