### ISSUE TITLE
Is it possible to hide tabs?

### ISSUE THREAD

**Issue by Lilian1331** [reactjs/react-tabs#287]
Hi all,
I am trying to hide tabs base on a different scenario.
I try to hide tabs with inline css. But it seems not working.
`<div style={{display:'none'}}><Tab></Tab></div>`

Any Helps, thanks.

**Comment by konekoya** [comment]
Do you have a reproducible example? I can help if you have one :)

**Comment by talseg** [comment]
did you try:
visibility: hidden

**Comment by Gary-Shurgin** [comment]
I am trying to set a hidden tab as visible, when I click on another tab.
How would I set this up?
