### ISSUE TITLE
Is it possible to have initially all tabs switched off?

### ISSUE THREAD

**Issue by hedgehog34** [reactjs/react-tabs#290]
I was wandering if this can be achieved in this component. So not tab selected and no content displayed.

**Comment by gabrieljbaker** [comment]
I'm wondering about this as well!

**Comment by gabrieljbaker** [comment]
@hedgehog34 looks like you can do it by setting selectedIndex or defaultIndex to -1

**Comment by danez** [comment]
@gabrieljbaker is correct.
