### ISSUE TITLE
Release null checks fix on 2.3.x branch

### ISSUE THREAD

**Issue by InvictusMB** [reactjs/react-tabs#295]
Hello @danez 
Could you please release 2.3.x patch version with https://github.com/reactjs/react-tabs/commit/83f8780d843cdc231e5deb561b456542a2b37a30 as well?

It is an especially annoying bug in combination with Material UI Select component.

https://stackblitz.com/edit/react-dxjmzk?file=index.js

**Comment by InvictusMB** [comment]
For some reason Material UI's `event.target` of `onChange` event is not a DOM node but a plain object. So `react-tabs` trips over it trying to traverse as if it was a DOM node.

The entire page crashes whenever you select an item of a Select  component that was rendered inside `react-tabs`.

**Comment by danez** [comment]
Done.
