### ISSUE TITLE
When adding padding to TabPanel it should not be pulled through to the non active panels

### ISSUE THREAD

**Issue by WillMayger** [reactjs/react-tabs#301]
To replicate:
1. Initiate a basic tab component with 2 tabs and 2 tab panels.
2. Add 20px padding to all tab panel components, using the className prop
3. navigate to the second tab.
4. notice how non active component's padding will show above the active tab panels component.
<img width="887" alt="Screenshot 2019-08-11 at 11 02 28" src="https://user-images.githubusercontent.com/8349503/62832549-60c8d900-bc28-11e9-9232-d56f21ca0972.png">

Expected:
Padding, and other styles related, should not be pulled through if the tab panel is not active
<img width="858" alt="Screenshot 2019-08-11 at 11 05 26" src="https://user-images.githubusercontent.com/8349503/62832555-69b9aa80-bc28-11e9-964c-89499af411f4.png">

**Comment by WillMayger** [comment]
PR for issue: https://github.com/reactjs/react-tabs/pull/302

**Comment by tomrndom** [comment]
I'm facing the same issue, is there any update on this?

**Comment by joepvl** [comment]
This is a styling issue; the padding is only showing because the DOM element isn't removed (and apparently it isn't hidden either), which is expected behaviour. You can style the inactive element to hide it more thoroughly using CSS if needed.
