### ISSUE TITLE
Warning: React does not recognize the `panelClassName` prop on a DOM element

### ISSUE THREAD

**Issue by DanielHeath** [reactjs/react-tabs#305]
When specifying a `panelClassName` via `<Tabs panelClassName="foo"/>`, the class name gets applied to UncontrolledTabs. Same for `tabClassName`.

```
Warning: React does not recognize the `tabClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `tabclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (created by ImageConsoleTabs)
```

**Comment by emilpalsson** [comment]
That is because `Tabs` does not take props called `panelClassName` or `tabClassName`. Only `selectedTabPanelClassName`, `disabledTabClassName`, and `selectedTabClassName`.

To set the className of a `Tab` or a `TabPanel`, simply pass `className` to them, and not to their `Tabs` parent.

**Comment by DanielHeath** [comment]
This

**Comment by jurgenrg** [comment]
Hi. Can you tell me where do you found the problem in the docs? I have the same problem.
