### ISSUE TITLE
react-tabs

### ISSUE THREAD

**Issue by sraj-ms** [reactjs/react-tabs#312]
Could not find a declaration file for module 'react-tabs'. 'xxx' implicitly has an 'any' type.
  Try `npm install @types/react-tabs` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-tabs';`  TS7016

**Comment by joepvl** [comment]
Do what the error message says. `npm install @types/react-tabs`.
See https://www.npmjs.com/package/@types/react-tabs
