### ISSUE TITLE
Add a `classNamesPrefix` prop for <Tabs> for changing BEM css project prefix

### ISSUE THREAD

**Issue by jnachtigall** [reactjs/react-tabs#313]
I just need to change the `className` prefix from `react-` to something like `myprj-`. At the moment for this to work I have to change various `className` props and `disabledTabClassName` and `selectedClassName`. It's time consuming and easy to forget one.

I need to do is because we use BEM with a project prefix always. To avoid css name conflicts.

At the moment this is what is needed (when you have actual content it is even more convoluted):
```jsx
<Tabs className="myprj-tabs">
  <TabList className="myprj-tabs__tab-list">
    <Tab
      className="myprj-tabs__tab"
      disabledClassName="myprj-tabs__tab--disabled"
      selectedClassName="myprj-tabs__tab--selected"
    >
      tab name
    </Tab>
  </TabList>
  <TabPanel
    className="myprj-tabs__tab-panel"
    selectedClassName="myprj-tabs__tab-panel--selected"
  >
    tab panel
  </TabPanel>
</Tabs>
```

Would be great if there was a `classNamesPrefix` so that one can easily override just the prefix. Default could be `react`.

```jsx
<Tabs classNamesPrefix="myprj">
  <TabList>
    <Tab>tab name</Tab>
  </TabList>
  <TabPanel>tab panel</TabPanel>
</Tabs>
```

**Comment by joepvl** [comment]
You can use the top-level [`disabledTabClassName`](https://github.com/reactjs/react-tabs#disabledtabclassname-string), [`selectedTabClassName`](https://github.com/reactjs/react-tabs#selectedtabclassname-string), and [`selectedTabPanelClassName`](https://github.com/reactjs/react-tabs#selectedtabpanelclassname-string) props instead for a little less verbosity, as suggested in the README. As applied to your code:
```jsx
<Tabs
  className="myprj-tabs"
  disabledTabClassName="myprj-tabs__tab--disabled"
  selectedTabClassName="myprj-tabs__tab--selected"
  selectedTabPanelClassName="myprj-tabs__tab-panel--selected"
>
  <TabList className="myprj-tabs__tab-list">
    <Tab className="myprj-tabs__tab">tab name</Tab>
  </TabList>
  <TabPanel className="myprj-tabs__tab-panel">tab panel</TabPanel>
</Tabs>
```

I get that it's verbose, but that's what you get with BEM. If you'd rather abstract all of that away for re-use, you can do so yourself by wrapping the components and using the `tabsRole` static property; see https://github.com/reactjs/react-tabs#custom-components.
