### ISSUE TITLE
Can't install with yarn: Couldn't find package

### ISSUE THREAD

**Issue by saletrak** [reactjs/react-tabs#314]
Hey, I tried to install this package, but i got a error after `yarn add react-tabs`. That's the output:

    > $ yarn add react-tabs
    yarn add v1.10.1
    [1/4] 🔍  Resolving packages...
    error Couldn't find package "form_components-data@~2.3.2" required by "request@^2.88.0" on the "npm" registry.
    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by joepvl** [comment]
I suggest you take another look at the error message; `react-tabs` doesn't use either of those packages directly or indirectly, so the error is definitely coming from somewhere else.
