### ISSUE TITLE
react-tabs issue 

### ISSUE THREAD

**Issue by softwaresolution357** [reactjs/react-tabs#320]
In React-tabs, 

Problem: React tabs contains three tabs 

1. tab 1 :  active and Inactive radio button

2. tab 2 : form tag and ck-editor 

3. tab 3: Image uploads 

In tab 1, I selected active button, when I go to tab 2, I am writing something ck editor and  form tag input field, when I go to tab 3, I upload the image input filed, 

 but image preview and active button data deleted.

I want hold data every field, Please help me

**Comment by joepvl** [comment]
Solution: use the `forceRenderTabPanel` prop to maintain state of not-selected `<TabPanel>`s in memory (see https://github.com/reactjs/react-tabs#forcerendertabpanel-boolean).
