### ISSUE TITLE
Tabs with WordPress

### ISSUE THREAD

**Issue by seanvarnham** [reactjs/react-tabs#323]
Hi,

I'm working on a block for the Gutenberg Editor and the tabbing is working fine on the backend, but if I use the tabs in the editor then it doesn't save properly in the frontend.

If I use RichText components in the backend it saves fine, but if attributeOne represents the content in the first panel and attributeTwo represents the content in the second panel, then I'm finding that the second tab (and third panel etc.) isn't clickable and attributeTwo doesn't appear in the DOM. It's as if there's no JS on the frontend.

Is there something that needs to be done for WP developments that I might be missing? I can post code if required.

Any help would be greatly appreciated.

Thanks!

**Comment by joepvl** [comment]
I don't think Gutenberg itself uses this package, if that's what you mean... other than that, if you are using it in your code and it isn't working, you'd have a better chance of getting an answer here if you isolate the problem to something related to react-tabs. However, in the end you're probably better off formulating the problem with more context and posting a question on StackOverflow. I personally don't know much about the specifics of developing with Wordpress, so can't help you there. Good luck!

**Comment by blt-sean** [comment]
Thanks @joepvl ,
I'll go to Stack to see if I can get help there, as you're right that it's not a part of the Gutenberg lib.
