### ISSUE TITLE
Deprecated lifecycle method warnings with React 16.13.1:

### ISSUE THREAD

**Issue by markvital** [reactjs/react-tabs#326]
The following warning is shown after upgrading to React 16.13.1:

    react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
    
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
    
    Please update the following components: Tabs

I'm using react-tabs version **3.1.0**

**Comment by astanciu** [comment]
BUMP. this is going to be an issue starting with React 17, when only the renamed "UNSAFE_xxx" methods will work... until React 18.

**Comment by danez** [comment]
Feel free to send PRs

**Comment by danez** [comment]
Version 3.0.0 and newer are not using any old lifecycle hooks. Maybe there is some other component called `Tabs` in your codebase or you have multiple versions of react-tabs?
The tests also work perfectly fine with react 17 without any deprecation warning.
