### ISSUE TITLE
Fixed Tab Header on scroll

### ISSUE THREAD

**Issue by tarun1992** [reactjs/react-tabs#340]
I just had a query regarding if there is any prop to make the tabs sticky on top while scrolling.

**Comment by joepvl** [comment]
There isn't as that would be outside the scope of this component, but it's definitely possible to achieve using CSS (depending on what you want the tabs to stick to). Try googling for `position: sticky` to get you started.

**Comment by tyn1998** [comment]
```javascript
        <Tabs>
          <TabList style={{position: 'sticky', top: 0}}>
            <Tab>System Details</Tab>
            <Tab>Vendor Details</Tab>
          </TabList>

          <TabPanel>
            <h2>Any content 1</h2>
          </TabPanel>
          <TabPanel>
            <h2>Any content 2</h2>
          </TabPanel>
        </Tabs>
```

This works!
