### ISSUE TITLE
UncontrolledTabs.js:46 Uncaught TypeError: Cannot read property 'oneOfType' of undefined

### ISSUE THREAD

**Issue by robertparts** [reactjs/react-tabs#346]
_Whats missing? 
My test.html_
```
<html>
<head>
	<script src="https://unpkg.com/react@16/umd/react.development.js"></script>
	<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
	<script src="https://unpkg.com/react-tabs@2/dist/react-tabs.development.js" />
	<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
</head>
<body><div>Hello!</div></body>
</html>
```
_result:_
```
UncontrolledTabs.js:46 Uncaught TypeError: Cannot read property 'oneOfType' of undefined
    at UncontrolledTabs.js:46
    at react-tabs.development.js:4
    at react-tabs.development.js:5
```

_UncontrolledTabs.js:46  there is:_
className: PropTypes.oneOfType([

Can anyone help?
Br. Robert

**Comment by joepvl** [comment]
From "Installing" in the readme:
> For example usages of the UMD builds have a look at the old_examples/umd folder. The development UMD build also needs the package prop-types being loaded besides react.

The solution can be found in `old_examples/umd/development.html` — add the following before react-tabs:
```html
<script src="https://unpkg.com/prop-types/prop-types.js"></script>
```

However, if you want to go down this route, I'd recommend copying all of the script tags from that example — the ones you've provided are outdated (old React Tabs and old Babel).
