### ISSUE TITLE
Retain tab index on back

### ISSUE THREAD

**Issue by akanksha033** [reactjs/react-tabs#350]
How can I retain the state of the last selected tab if I'm coming back from a page. For example : if I have tab1 and tab2 and on clicking on a link on tab2 I reach a page, now on clicking the back button I want to land on the last selected tab. The tab is setting to 0 as it is re-rendering on clicking the back button.

**Comment by joepvl** [comment]
I'm closing this as this issue/question is not specific to this library.

I can give you a bit of direction, though: you'll want to have some logic in the function you pass to [`onSelect`](https://github.com/reactjs/react-tabs#onselect-index-number-lastindex-number-event-event--boolean) to save the selected index somehow, so it's available for you to pass it to [`selectedIndex`](https://github.com/reactjs/react-tabs#selectedindex-number) when the component is mounted again.
For example, you could save it to the state of a higher-up component, to a context, or to some state management solution (or, if clicking the link causes a page reload, you'll want to persist it to e.g. `localStorage` so you can retrieve it when the component is mounted when the user navigates back). Another option would be to synchronize the selected tab with a part of the URL, either using a router solution or some other scheme.

This is a problem you'll run into with anything that is unmounted (causing its internal state to be cleared from memory) and needs to restore its state when the user comes back to the view it was rendered in earlier. It's not specific to React Tabs, React, or even web development in general.
