### ISSUE TITLE
Is there a way to disable focus from tabs?

### ISSUE THREAD

**Issue by apodacaduron** [reactjs/react-tabs#371]
Hi, I know that the focus is used for accessibility, but currently I'm having some issues to do what I need, I'm building a component that allows tabs to be renamed, but the tab is stealing the focus from my inputs, the idea is to double click the text to make an input appear, or single click the pencil to use the input (in my demo double clicking doesn't work either but in my project does, I'm having issues with single clicking the pencil).

Tried to do demo as close as my code:
https://codepen.io/apodacaduron/pen/GRNJNaR

My project:
[Video Sample](https://user-images.githubusercontent.com/47479471/106554170-113f3280-64d8-11eb-9926-3cd24dc6d3bc.mov)

**Comment by Kanha-13** [comment]
Hi I just found the bug, and what I found is the input get focus only when the Default tab is selected. And then if you click on pencil icon it works

**Comment by alexHlebnikov** [comment]
Same problem here. Is there a way to fix it?

**Comment by danez** [comment]
The example now works correctly with version 4.2.0 of `react-tabs`. There is also a new prop `focusTabOnClick` to be able to siable focus completely on click.
