### ISSUE TITLE
Renovate bot missing github workflow permission

### ISSUE THREAD

**Issue by danez** [reactjs/react-tabs#382]
Hi @bvaughn, @gaearon,

Sorry for pinging, but not sure who else I should talk to and who is admin of the @reactjs org.

In the @reactjs org, renovate-bot is setup, but recently they added a new permission it needs, namely the `workflow` permission.
I myself am not an admin, so can someone of you please check the settings of the org and grant the new permission?

Thanks in advance

**Comment by bvaughn** [comment]
I don't know much about the Renovate bot (like how it's different from Dependabot) but why did it recently start asking for access to member names and emails? That made me a little suspicious.

Looks like a more detailed explanation of this is covered here:
https://github.com/renovatebot/config-help/issues/358

Seems okay I guess.

**Comment by danez** [comment]
Thank you
