### ISSUE TITLE
react-tabs.css CDN 404ing

### ISSUE THREAD

**Issue by AdnanTheExcellent** [reactjs/react-tabs#400]
it is listed as a method to import react-tabs.css using the unpkg CDN:

https://www.npmjs.com/package/react-tabs

however, the url https://unpkg.com/react-tabs/style/react-tabs.css just starting giving a 404 error

this currently broke my site as of a few minutes ago. i'm currently looking for a workaround in the meantime

**Comment by danez** [comment]
It seems to work now again. 
I don't have control how it is hosted there as the service simply hosts the npm package.
If this happens more often please report this to unpkg.com
