### ISSUE TITLE
Problem using TabList className attribute

### ISSUE THREAD

**Issue by studiojms** [reactjs/react-tabs#404]
TabList component's style is being overridden by `className` attribute.

When we have a `TabList` with specific `className`, the default value of `className` ("**react-tabs__tab-list**") is being replaced by the content of `className` attribute, and not appended (as expected).

Example: https://codepen.io/studiojms/pen/MWpLNJN

**Comment by danez** [comment]
This is expected.

If you still want the default class-names you need to add them to the prop `className="yourclass react-tabs__tab-list"`

The idea is that in most cases you want to copy the default styles and adjust them to your liking anyway.
