### ISSUE TITLE
Symbol.iterator is undefined

### ISSUE THREAD

**Issue by yann300** [reactjs/react-tabs#429]
We are trying to integrate the tabs in our project ( https://github.com/ethereum/remix-project ) but our production build produces this errors at runtime:
`Unhandled promise rejection TypeError: Object is not iterable.`
The underlying issue is " `Symbol.iterator` is undefined"
It seems linked to the fact that we use a different version of webpack but I couldn't verify that..

So I understand the issue could be from our side, but just checking if you already experienced this issue?

**Comment by danez** [comment]
There might be polyfills missing. Which browser are you running the project in?
