### ISSUE TITLE
style tag support?

### ISSUE THREAD

**Issue by zebapy** [reactjs/react-tabs#44]
I'm using inline styles for my app. it'd be nice if I could continue to just add `style` attributes to style the `Tabs`, etc. I tried doing this but doesn't seem they're allowed.

**Comment by ihsansatriawan** [comment]
:+1:

**Comment by MarinaaaniraM** [comment]
I could't use styles for <TabList> and <Tab>.  I tried: style={styles.tab}

**Comment by danez** [comment]
This is now possible in 0.6
