### ISSUE TITLE
controller focus event is kept on every render

### ISSUE THREAD

**Issue by ranYaar** [reactjs/react-tabs#451]
Hi, 
iv upgraded from version 3.2.3 to latest version, currently the tab focus event is called on every render of the view, making other inputs on the view to lose their focus.
in my case the view is render from time to time making a search for example very hard..
thanks

**Comment by danez** [comment]
Thanks for reporting i will have a look at it soon.

**Comment by danez** [comment]
This should be fixed with 4c63bcb057f82de498bbb3325556f6d26064aa8e and version 4.2.0

Can you please check and if not fixed reopen this ticket.
