### ISSUE TITLE
UncontrolledTabs.js Eror:   Uncaught TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.useId) is not a function

### ISSUE THREAD

**Issue by Gurinder-Batth** [reactjs/react-tabs#477]

**Comment by benb1983** [comment]
Same issue

**Comment by AwolDes** [comment]
Yep, getting a similar error too

![image](https://user-images.githubusercontent.com/9693812/168739261-cd8867ff-4a2b-4aa0-9129-132f4ab690ca.png)

**Comment by danez** [comment]
How do you use react-tabs? Installed via npm or umd bundle?
Where/when does the error appear? In the browser at runtime or during build?

**Comment by danez** [comment]
Okay I just noticed that the error is about `useId`. 
The latest version (v5) of `react-tabs` does require react 18.0.0 as a minimum.
If you happen to use an older react version please use `react-tabs` version 4.

**Comment by quantum-quant** [comment]
I still have the same issue even after using reac-tabs version 4 with an older react version (17.0.2)
