### ISSUE TITLE
Issues when implementing the same Tabs for different TabPanels

### ISSUE THREAD

**Issue by mariela-plaza** [reactjs/react-tabs#481]
I want to implement an idea using react-tabs where I change the content displayed in the TabPanels depending on a particular state.
I have tried to implement this by having a parent component (AppTabs) that depending on the value of the state (let's call it mode) it renders one of two different components: Tables or Graphs.

These two components return the TabPanels with the content that each of them should render.

Here is the code:
**AppTabs:**
![image](https://user-images.githubusercontent.com/24737923/174743541-b6bb0e03-198c-45c1-b663-476c534aeb64.png)

**Tables:**
![image](https://user-images.githubusercontent.com/24737923/174743706-25d6c391-3100-4b79-8321-e8db8cc8916a.png)

**Graphs:**
![image](https://user-images.githubusercontent.com/24737923/174743793-de3cf616-7af8-45f2-a56d-0bce046f3b72.png)

When I try to execute this, I get the following error message:

_Warning: Failed prop type: There should be an equal number of 'Tab' and 'TabPanel' in `Tabs`. Received 2 'Tab' and 0 'TabPanel'._

Does this mean that I need to declare all of the pieces of react-tabs (Tab, Tabs, TabList, TabPanel) in the same component or else it won't work? Or am I doing something wrong?

I want to do it this way because then I could have all of the states regarding the Tables component or the Graphs component separated. Otherwise, I would need to set all of the states for both of these components in AppTabs and I think that would be very cluttered and a nightmare to maintain.

Thank you for you feedback in advance! Have a great day!

**Comment by joepvl** [comment]
Hi Mariela. Unfortunately there is no way to declare your `TabPanel`s in a separate component; the `Tabs` component can't detect them through the component boundary. However, a simple solution in this case would be to turn the `Tables` and `Graphs` components into render functions:

```jsx
function renderTables() {
  return (
    <React.Fragment>
      <TabPanel>Table content 1</TabPanel>
      <TabPanel>Table content 2</TabPanel>
    </React.Fragment>
  );
}

function renderGraphs() {
  return (
    <React.Fragment>
      <TabPanel>Graph content 1</TabPanel>
      <TabPanel>Graph content 2</TabPanel>
    </React.Fragment>
  );
}

function AppTabs({ mode }) {
  return (
    <Tabs className="tabs">
      <TabList>
        <Tab>title 1</Tab>
        <Tab>title 2</Tab>
      </TabList>
      {mode === 'tables' && renderTables()}
      {mode === 'graphs' && renderGraphs()}
    </Tabs>
  );
}
```

Another way to solve this particular issue would be to pass the `mode` to the components you render inside the `TabPanel`s and use that to decide what to render from inside the component.

**Comment by mariela-plaza** [comment]
Hi joepvl, thank you for your answer!
The code I provided is from a pet project that simplifies what I want to achieve in the real project I am working on.

The issue is that in this real project, the Tables and Graphs component would have their own states and a lot of complex logic that would unique to each one. That is why I can't turn them into render functions.

I also thought about implementing the second solution you suggested, but that would mean that all of the states and complex logic that I want to use in the Tables and Graphs components would need to be declared in the AppTabs component, which would make said component quite cluttered and difficult to work with.


I appreciate very much your input, it gives me a lot more clarity on what I can do and can't do with the project at hand :)
Have a great day, kind regards!
