### ISSUE TITLE
How I can fix this error in  react version dependency?

### ISSUE THREAD

**Issue by MindBreakerGM** [reactjs/react-tabs#486]
![изображение](https://user-images.githubusercontent.com/58743402/181678716-7bfaa288-e2b5-4c87-95ad-de07ff25ba1e.png)

**Comment by MindBreakerGM** [comment]
Not working --legacy-peer-deps

**Comment by joepvl** [comment]
React Tabs v5 requires React 18 or newer. So you can either upgrade your project to React 18 or use React Tabs v4.
