### ISSUE TITLE
Why select first tab by default?

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-tabs#49]
I mean, if the passed model has not an active tab, why should we open one by default?
Doesn't it leads to inconsistence with the data model and the view?

Thanks.

**Comment by danez** [comment]
I think it is just done because usually most tabs on the web are always open initially. 
If it is a usecase for you to have the tabs initially not render any tabpanel, fell free to create PR that makes it possible to not open a tabpanel on initial render.

**Comment by lauterry** [comment]
Hi

If you don't want any tab to be active, there is a workaround.

You can set the selectedIndex to a value greater than the maximum tab count.

**Comment by danez** [comment]
This will be fixed in 1.0.0 by setting `selectedIndex` or `defaultIndex` to -1
