### ISSUE TITLE
when set state on selected, tabs dont change

### ISSUE THREAD

**Issue by shangsunset** [reactjs/react-tabs#51]
So, when i try to so `this.setState({})` on select, the code in `handleSelected` will be executed but the tabs will stop changing.

```javascript

  handleSelected(index, last) {
    console.log('Selected tab: ' + index + ', Last tab: ' + last);
    if (index == 1) {

      console.log(index);
      this.setState({paymentType: 'paypal'})
    }
    else {

      this.setState({paymentType: 'creditcard'})
    }
  }
```

**Comment by austinknight** [comment]
Same for me too

**Comment by austinknight** [comment]
I ended up wrapping the functionality I wanted to execute within my handleSelected function in a setTimeout of 0 and the tabs changed as expected and executed everything inside.

**Comment by otmjka** [comment]
The same situation.

**Comment by mcohoon** [comment]
@austinknight can you provide more detail on your solution. I am new to React and I have run into the same issue.

**Comment by joepvl** [comment]
You can always work around this by using `Tabs` as a controlled component, e.g.:

```javascript
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      selectedIndex: 0
    };

    this.handleSelected = this.handleSelected.bind(this);
  }

  handleSelected(index, last)  {
    this.setState({
      selectedIndex: index,
      //...otherStateUpdates
    });
  }

  render() {
    return <Tabs
      onSelect={ this.handleSelected }
      selectedIndex={ this.state.selectedIndex }
    >
      { /* <TabList>, <Tab>s, <TabPanel>s */ }
    </Tabs>
  }
}
```

That said, this is a bug, or at least it seems like unintended behaviour from reading the docs and [the source](https://github.com/reactjs/react-tabs/blob/4e720269ad4a013a8e9539c22db616d0286ae48e/src/components/Tabs.js#L89). There seems to be a race condition relating to `setState`'s async nature. I've started investigating this, so more to follow. In the mean time, a reproduction can be found here: http://jsbin.com/patociheze/edit?js,console,output. I've also written a failing test, but not sure how to proceed. I'll probably make a PR with that tomorrow to get feedback.

**Comment by nicotroia** [comment]
Has this been fixed? I'm on 0.8.2 and still running into this issue... using a setTimeout isn't working either

**Comment by joepvl** [comment]
@nicotroia can you provide some example code that shows what you're trying to accomplish? I just tried the focus example with 0.8.2 and it seems to work fine.

**Comment by nicotroia** [comment]
@joepvl It was a syntax error within the same parent component that decided not to throw any errors or warnings. Everything works now, thanks 👍

**Comment by joepvl** [comment]
Excellent. 🙂
