### ISSUE TITLE
defaultProps warning - Support for defaultProps will be removed from function component will be removed

### ISSUE THREAD

**Issue by bsejawal** [reactjs/react-tabs#514]
I am getting following warning on React project with react-tabs. Can we resolve that warning? Thanks
![tabs-defaultProp-warning](https://user-images.githubusercontent.com/3782836/228652533-ecf91ff6-d35c-47e7-b0d1-a5f63d39a227.png)

**Comment by danez** [comment]
Thanks for reporting

**Comment by bsejawal** [comment]
Sure, @danez that would be very helpful. Because there are same errors with this simple one and console is messy. I believe, you can fix this quickly.

**Comment by bsejawal** [comment]
@danez do you have any updates on this? thanks

**Comment by bsejawal** [comment]
@danez any update here? please let me know

**Comment by danez** [comment]
No update. As I said I'm happy to accept a pull request.
