### ISSUE TITLE
AntiPattern getInitialState

### ISSUE THREAD

**Issue by jamesjjk** [reactjs/react-tabs#58]
Hi, whilst looking further at the component to possibly fix the serverside rendering issue I noticed the copyPropsToState - this seems like an antipattern why do this here?

https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html
getInitialState() {
    return this.copyPropsToState(this.props);
  },

**Comment by SylarRuby** [comment]
Many components I see today still uses the antipattern. I have to rewrite their code.
