### ISSUE TITLE
Two copies of React are loaded due to peerDependencies

### ISSUE THREAD

**Issue by whs** [reactjs/react-tabs#88]
As react-tabs has react listed as peerDependencies, npm will install another copy of React that is compatible with the listed version.

If the application requires another incompatible version, it will cause two copies of React to be loaded. As React does not support loading multiple versions on the same page, the application will break.

I propose that the peerDependencies in package.json should be moved to devDependencies.

**Comment by danez** [comment]
With the latest updated  `peerDependencies` this should not be a problem anymore. Also you might want to consider on using npm version 3 where peerDependencies are not installed anymore if missing.
