### ISSUE TITLE
use keyboard tab to focus tabs doesn't work.

### ISSUE THREAD

**Issue by suhaotian** [reactjs/react-tabs#95]
in latest chrome, tab keyboard doesn't focus tabs

**Comment by reintroducing** [comment]
FYI this works fine for me on Version 51.0.2704.63 (64-bit) OSX El Capitan 10.11.3.

**Comment by danez** [comment]
Works for me also just fine. Please provide more details on how you use the tabs and what is the version of chrome you use.

**Comment by suhaotian** [comment]
Keyboard tab always can focus tabs, but can't navigate focused tabs. arrow key did it.
close it.
