### ISSUE TITLE
Can't suppress click events when clicking on tabs.

### ISSUE THREAD

**Issue by PAK90** [reactjs/react-tabs#97]
The tabs I'm using are in a div which has an onClick event, which triggers whenever I click on a tab (since it's in the div). I want to suppress this, and have been using the code `onClick={(evt) => this.suppressClick(evt)}` to accomplish this elsewhere. However, it doesn't work (as in, it won't enter the `suppressClick` function at all) in the tab code, no matter where I put it; I've tried to put it as a property in the `<TabList>` and `<Tab>` tags to no avail. I know it works in `<div>`s so I put one around the `<tab>` tags but that disabled clicking on the tabs entirely. What's the recommended method to disable click event propagation for these tabs?

**Comment by danez** [comment]
Since you posted a lot of things have changed. Sorry that no one responded.

I think with the latest version supplying `onClick` on the tab and tablist should work.
Otherwise it is now also possible to put a `<div>` around  the `<TabList>` component and put the onClick there.
